"""
figma MCP Server - Generated by Rehoboam
Figma MCP Server for MVP

Integrated with Dhumavati's Zero Point Module for hive_mind processing.
"""

import os
import json
import logging
import asyncio
from typing import Dict, Any, List, Optional
from datetime import datetime
from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
from pydantic import BaseModel
import httpx

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("figma")

app = FastAPI(
    title="figma MCP Server",
    description="Figma MCP Server for MVP",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Configuration
USER_WALLET = "0x9b9C9e713d8EFf874fACA1f1CCf0cfee7d631Ae8"
SOLANA_WALLET = "Dk5jYpSP3U9PTeHdWUooztu9Y5bcwV7NUuz8t3eemL2f"
PORT = int(os.getenv("PORT", "3110"))
REGISTRY_URL = os.getenv("REGISTRY_URL", "http://mcp-registry:3001")

# MCP Functions registry
mcp_functions = {}

class MCPRequest(BaseModel):
    function_name: str
    parameters: Dict[str, Any] = {}

class MCPResponse(BaseModel):
    success: bool
    result: Any = None
    error: str = None
    execution_time: float = None


async def hello_world() -> str:
    """Returns a greeting message"""
    try:
        return "Hello from figma MCP Server!"
    except Exception as e:
        logger.error(f"Error in hello_world: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

mcp_functions["hello_world"] = {
    "func": hello_world,
    "description": "Returns a greeting message",
    "parameters": {},
    "return_type": "str"
}

async def process_data(data) -> Dict[str, Any]:
    """Process input data with hive_mind enhancement"""
    try:
        
                # HiveMind-enhanced data processing
                processed = {
                    "original_data": data,
                    "processed_timestamp": datetime.now().isoformat(),
                    "hive_mind_enhancement": 0.8,
                    "user_wallet": USER_WALLET
                }
                return processed
    except Exception as e:
        logger.error(f"Error in process_data: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

mcp_functions["process_data"] = {
    "func": process_data,
    "description": "Process input data with hive_mind enhancement",
    "parameters": {"data": "any"},
    "return_type": "Dict[str, Any]"
}


async def get_file(file_id: str):
    """Fetch a Figma file by file_id (file key)."""
    token = os.getenv("FIGMA_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="FIGMA_TOKEN not set")
    async with httpx.AsyncClient() as client:
        headers = {"X-Figma-Token": token}
        resp = await client.get(f"https://api.figma.com/v1/files/{file_id}", headers=headers, timeout=30)
        if resp.status_code != 200:
            raise HTTPException(status_code=resp.status_code, detail=resp.text)
        return resp.json()

mcp_functions["get_file"] = {
    "func": get_file,
    "description": "Get Figma file metadata",
    "parameters": {"file_id": "str"},
    "return_type": "dict"
}

async def get_nodes(file_id: str, node_ids: str):
    """Get nodes from a Figma file. node_ids is a comma-separated list of node IDs."""
    token = os.getenv("FIGMA_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="FIGMA_TOKEN not set")
    params = {"ids": node_ids}
    async with httpx.AsyncClient() as client:
        headers = {"X-Figma-Token": token}
        resp = await client.get(f"https://api.figma.com/v1/files/{file_id}/nodes", headers=headers, params=params, timeout=30)
        if resp.status_code != 200:
            raise HTTPException(status_code=resp.status_code, detail=resp.text)
        return resp.json()

mcp_functions["get_nodes"] = {
    "func": get_nodes,
    "description": "Get specific nodes from a Figma file",
    "parameters": {"file_id": "str", "node_ids": "str (comma-separated)"},
    "return_type": "dict"
}

async def get_images(file_id: str, ids: str, format: str = "png"):
    """Get rendered image URLs for nodes in a Figma file. ids is comma-separated list."""
    token = os.getenv("FIGMA_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="FIGMA_TOKEN not set")
    params = {"ids": ids, "format": format}
    async with httpx.AsyncClient() as client:
        headers = {"X-Figma-Token": token}
        resp = await client.get(f"https://api.figma.com/v1/images/{file_id}", headers=headers, params=params, timeout=30)
        if resp.status_code != 200:
            raise HTTPException(status_code=resp.status_code, detail=resp.text)
        return resp.json()

mcp_functions["get_images"] = {
    "func": get_images,
    "description": "Get image URLs (renders) for nodes in a Figma file",
    "parameters": {"file_id": "str", "ids": "str (comma-separated)", "format": "str (png|jpg|svg)"},
    "return_type": "dict"
}

async def get_comments(file_id: str):
    """Get comments for a Figma file."""
    token = os.getenv("FIGMA_TOKEN")
    if not token:
        raise HTTPException(status_code=500, detail="FIGMA_TOKEN not set")
    async with httpx.AsyncClient() as client:
        headers = {"X-Figma-Token": token}
        resp = await client.get(f"https://api.figma.com/v1/files/{file_id}/comments", headers=headers, timeout=30)
        if resp.status_code != 200:
            raise HTTPException(status_code=resp.status_code, detail=resp.text)
        return resp.json()

mcp_functions["get_comments"] = {
    "func": get_comments,
    "description": "Get comments for a Figma file",
    "parameters": {"file_id": "str"},
    "return_type": "dict"
}

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "user_wallet": USER_WALLET,
        "functions": list(mcp_functions.keys())
    }

@app.get("/functions")
async def list_functions():
    """List all available MCP functions."""
    return {
        "functions": {
            name: {
                "description": info["description"],
                "parameters": info["parameters"],
                "return_type": info["return_type"]
            }
            for name, info in mcp_functions.items()
        }
    }

@app.post("/execute", response_model=MCPResponse)
async def execute_function(request: MCPRequest):
    """Execute an MCP function."""
    start_time = datetime.now()
    
    if request.function_name not in mcp_functions:
        raise HTTPException(status_code=404, detail=f"Function {request.function_name} not found")
    
    try:
        func_info = mcp_functions[request.function_name]
        result = await func_info["func"](**request.parameters)
        
        execution_time = (datetime.now() - start_time).total_seconds()
        
        return MCPResponse(
            success=True,
            result=result,
            execution_time=execution_time
        )
    
    except Exception as e:
        execution_time = (datetime.now() - start_time).total_seconds()
        logger.error(f"Function execution error: {str(e)}")
        
        return MCPResponse(
            success=False,
            error=str(e),
            execution_time=execution_time
        )

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """WebSocket endpoint for real-time MCP communication."""
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            message = json.loads(data)
            
            if message.get("type") == "execute":
                request = MCPRequest(**message.get("data", {}))
                response = await execute_function(request)
                await websocket.send_text(json.dumps({
                    "type": "result",
                    "data": response.dict()
                }))
            
    except WebSocketDisconnect:
        logger.info("WebSocket client disconnected")

async def register_with_registry():
    """Register this server with the MCP registry."""
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(f"{REGISTRY_URL}/api/servers/register", json={
                "name": "figma",
                "url": f"http://figma:{PORT}",
                "capabilities": list(mcp_functions.keys()),
                "metadata": {
                    "description": "Figma MCP Server for MVP",
                    "version": "1.0.0",
                    "generated_by": "Rehoboam MCP Generator",
                    "user_wallet": USER_WALLET,
                    "hive_mind_layer": "True"
                }
            })
            
            if response.status_code == 200:
                logger.info("Successfully registered with MCP registry")
            else:
                logger.warning(f"Failed to register with MCP registry: {response.status_code}")
                
    except Exception as e:
        logger.warning(f"Could not register with MCP registry: {str(e)}")

if __name__ == "__main__":
    # Register with registry on startup
    asyncio.create_task(register_with_registry())
    
    logger.info(f"Starting figma MCP Server on port {PORT}")
    logger.info(f"User wallet: {USER_WALLET}")
    logger.info(f"Available functions: {list(mcp_functions.keys())}")
    
    uvicorn.run(app, host="0.0.0.0", port=PORT)